Added html img component instad of next/image when using srcSet
Automattic/vip-go-nextjs-skeleton pull request #49
Opened 2021-12-29 18:54 UTC by luiztiago

## Summary

- Added the `<img />` component instead of next/image when using `srcSet`
- It has been added on PostContent file, to be used on Group Blocks.

## Notes

- Added the `@next/next/no-img-element` on the eslint rules, because was getting an error to don't use the `<img />` tag.
- `components/PostContent/PostContent.tsx` line 27 was added to prevent warning on if statement.

2021-12-30 14:13 UTC, elazzabi approved these changes
I think this looks good, but I have a question.

So it looks like the presence of `srcSet` in the props is what decides if we'll use `<img>` or `Image`. However, from our WP bundle, it looks like the `srcSet` attribute [will always be there](https://github.com/Automattic/vip-decoupled-bundle/blob/5f31805fa96746f1853fd781308d6b13f57eaed0/blocks/blocks.php#L94) and [we ask for all attributes by default](https://github.com/Automattic/vip-go-nextjs-skeleton/blob/trunk/graphql/fragments/ContentNode.graphql#L9). So, in theory, we'll always use `<img>` 🤔 . If that's true, I guess we should document it.

2021-12-30 17:15 UTC, luiztiago commented
@elazzabi Make sense, I did some tests here, and you're right. So maybe we can add a config inside the `next.config.js` file and check it inside the if statement. What do you think?

2021-12-30 17:57 UTC, luiztiago commented
@elazzabi I did the update with the config approach. Let me know what do you think about it.

2021-12-30 17:58 UTC, luiztiago commented on components/PostContent/PostContent.tsx
> +import config from '../../next.config';
I added the `config` in lowercase because is the pattern on all files importing `next.config.js` file

2021-12-31 10:16 UTC, elazzabi requested changes
I changed a few things locally to make it work, I posted them as suggestions.

I think the config approach is good to make this configurable by customers 👍

2021-12-31 10:16 UTC, elazzabi commented on components/PostContent/PostContent.tsx
> +								srcSet: blockProps.srcSet || undefined,
```suggestion
								srcSet: blockProps.srcset || undefined,
```

Looks like the attribute we return from WP is `srcset` instead of `srcSet`

2021-12-31 10:16 UTC, elazzabi commented on components/PostContent/PostContent.tsx
> +									<img alt={blockProps.alt} {...defaultProps} />
```suggestion
									<img alt={blockProps.alt} {...imageProps} />
```

This should pass `imageProps` in order for `srcSet`, `src`, `width` and `height` to be populated

2022-01-04 02:30 UTC, luiztiago commented
@elazzabi Talking with @chriszarate today, we had the idea to create a new file with the vip.configs to keep the `next.config.js` file with only the settings from next.js. I moved the logic and comments to the new file and worked on your requests. Thanks :)

2022-01-04 09:29 UTC, elazzabi approved these changes
> create a new file with the vip.configs to keep the next.config.js file with only the settings from next.js

Sounds like a good idea!

This should be good to go after merging the last suggested change ^

2022-01-04 17:46 UTC, luiztiago commented
@elazzabi Can you double-check the last suggested change? If I understood your request, it's already been done.

2022-01-06 09:12 UTC, elazzabi commented
@luiztiago Hmm weird, it still shows that we are using `defaultProps` instead of `imageProps` 🤔

2022-01-06 13:23 UTC, luiztiago commented
@elazzabi It's fixed now, sorry I misunderstood your request before.

2022-01-11 18:32 UTC, luiztiago commented
@elazzabi Hey, just a reminder, if you can approve it again because I did some updates after your first approval :)

2022-01-11 18:47 UTC, chriszarate approved these changes

2022-01-11 18:50 UTC, merged