Add configuration for local wp-env setup
Automattic/vip-go-nextjs-skeleton pull request #96
Opened 2022-08-02 09:41 UTC by alecgeatches

When I first ran this skeleton project for testing, I was hoping for a `docker-compose up`-type setup I could use to get the skeleton running against a local WordPress instance. It's currently a bit tricky to do, especially if a developer doesn't already have a test WordPress server running. A interested developer must currently:

1. Setup a cloud/local docker/`wp-env`/`vip dev-env` WordPress server
2. Install [vip-decoupled-bundle](https://github.com/Automattic/vip-decoupled-bundle) on the WordPress server through cloning the repository or using a GitHub zip download of the repository
3. Configure `.env` constants to point to the server
4. Run the NextJS code in this repository

My goal is replace the first three steps with a local WordPress setup and provide configuration defaults so it'll be ready to go right away.

I've decided to use `wp-env` for the server setup over `docker-compose` configuration or `vip dev-env` as the [decoupled plugin bundle](https://github.com/Automattic/vip-decoupled-bundle) already uses `wp-env`, and it's easy to use to auto-pull and install plugins.

The result of this PR should either be:

1. A setup where `.env` points to a local WordPress installation, and we provide instructions on installing `wp-env` to get thing running, or
5. A documentation section for quick local setup

2022-08-02 12:49 UTC, chriszarate approved these changes
Nice! Approving now, but should wait to merge until https://github.com/Automattic/vip-decoupled-bundle/pull/57 is merged and we can target the trunk branch

2022-08-03 06:00 UTC, alecgeatches commented
Thank you @chriszarate! I'm still diagnosing an issue getting data requests to work from NextJS on `localhost:3000` -> GraphQL endpoint on `localhost:8888`. This is still a work in progress. I may need to make some other code changes here to get the setup working, and I'll let you know when those are ready for review!

2022-08-03 07:00 UTC, alecgeatches commented
I found an issue, and it doesn't seem to be related to `localhost` specifically. It seems like for pathname resolution to work properly, permalinks in WordPress must be set to a non-default value:

![permalink-settings](https://user-images.githubusercontent.com/17870752/182542746-9c614c64-b242-4b7b-97d9-e896bb27781c.png)

Using the default setting "Plain" (`http://localhost:3000/?p=123`) causes NextJS to produce broken links to pages and posts. For example, here's what `<PostList>` generates on the [default Pages section](http://localhost:3000/latest/page) with default permalinks:

```html
<ul>
  <li>
    <a href="/latest/[content_type]?page_id=2">Sample Page</a>
  </li>
</ul>
```

This `href` value looks strange, and when clicked generates an error:

![Screen Shot 2022-08-02 at 5 14 56 PM](https://user-images.githubusercontent.com/17870752/182543337-deefa770-817a-4ec3-b98a-d4896c1f1775.png)

This network error seems to be due to the odd URL with square-brackets.

---

If the WordPress permalinks configuration is updated to use "Post name" (`http://localhost:3000/sample-post/`) like the [default content hub backend](https://node-content-hub.go-vip.net/hello-world), then everything works. Here's the resulting output of `<PostList>` with the updated permalink structure:

```html
<ul>
  <li>
    <a href="/sample-page">Sample Page</a>
  </li>
</ul>
```

Clearly something's mangling up plain page references. I'm going to look into supporting the default WordPress page route setup in the skeleton.

2022-08-03 09:44 UTC, alecgeatches commented
@chriszarate Okay, I found a solution! Here's a quick rundown of the problem I'm trying to fix:

1. By default, WordPress uses a query string-based parameter style for loading a page (e.g. `http://site.com/?p=1`).
2. When creating a `wp-env` environment, this default is used. One possible soultion could make this environment use slug-based permalinks to match our expectations, but as far as I know there is no way to pass a permalink structure via config values in `.wp-env.json` to set permalink structure during setup. Also ideally we should be able to support a default WordPress setup backend.
3. The code in this repository expects pages and posts are referred to by slug [as described above](https://github.com/Automattic/vip-go-nextjs-skeleton/pull/96#issuecomment-1203562259), and chokes when query-string based URLs like `/?p=1` are present.

My solution was to include the post slug [in the `ContentNode` query](https://github.com/Automattic/vip-go-nextjs-skeleton/blob/52e38a2874133e1b785b00ec1e861c2acbaef353/graphql/fragments/ContentNode.graphql#L28), and [use `slug` as a fallback](https://github.com/Automattic/vip-go-nextjs-skeleton/blob/52e38a2874133e1b785b00ec1e861c2acbaef353/lib/links.ts#L65-L67) when a query string is encountered in a URL. I commented on some [other possible solutions in this commit](https://github.com/Automattic/vip-go-nextjs-skeleton/pull/96/commits/b53c6b669c8177e035983f1eb8beb9fa1e92073a), but I dropped those ideas for now.

This seems to work great, but I'm not an expert here and would love a review. Thank you!

2022-08-04 04:27 UTC, alecgeatches commented
I have added documentation for the local setup, and tested that the workaround works properly for the default WordPress plain permalink setup (`/?p=1`), simple slug permalinks (`/page-slug`) and long date slug permalinks (`/2022/08/page-slug`).

2022-08-10 22:05 UTC, chriszarate requested changes
Nice work on this @alecgeatches! I've taken this for a spin and have some thoughts and questions:

1. I like the change to `.env` to point to the local environment. I think that makes sense. What I'd like to see is an additional env file that demonstrates how to override it for other environments. I think a `.env.production` makes the most sense for this use case.
2. I appreciate the effort to support "plain" permalinks (`?p=x`), but I think there are way too many edge cases to cover here. Additionally, plain permalinks are not good practice, for SEO and other reasons. I think we can add:
    - A setup step to set the permalink structure of the local WordPress instance, e.g., `wp-env run cli "wp rewrite structure '/%year%/%monthnum%/%day%/%postname%/'"`
    - Documentation that explains which permalink structures we support (basically, any permalink structure that includes the slug / `%postname%`)

2022-08-11 07:29 UTC, alecgeatches commented
> plain permalinks are not good practice, for SEO and other reasons

@chriszarate That's a good enough reason to include a permalink setup step and not support the default. I've never encountered plain permalinks in real-world WordPress setups and I suppose that's why. I'll change the documentation here to include that step, as well as the production example you've included. Thanks!

2022-08-12 03:10 UTC, alecgeatches commented
@chriszarate I've made those changes and am ready for another review. Thanks!

2022-08-15 02:18 UTC, chriszarate approved these changes
👍 Thanks for these improvements!

2022-08-15 02:58 UTC, merged